### ISSUE TITLE
E518: Unknown option: <M-/>=^[/

### ISSUE THREAD

**Issue by stesen** [aben20807/vim-commenter#5]
I get error on start

> Error detected while processing function commenter#MapMetaKey:
> line    1:
> E518: Unknown option: <M-/>=^[/
> Press ENTER or type command to continue

test on mintty+ssh and mobaxterm, neovim

**Comment by aben20807** [comment]
Hi, stesen
The main editor I use is not neovim but vim (in Ubuntu or Cygwin).
I will try to check what happen in the other environment or editor.
Thank you for opening this issue.

**Comment by aben20807** [comment]
@stesen 
I try this plugin in neovim (in Ubuntu 16.04) and there is no error.
Moreover, I am sorry about that I will not test in mobaxterm.
Due to above, I close this issue.
(Maybe try this after commenting that line)
Feel free to reopen this issue if you have other advice. Thanks.

**Comment by aben20807** [comment]
I have changed the map behavior only map `<M-/>` when n, i or v key using `<M-/>`.
Try to not map `<M-/>` but other key, like:
```vim
let g:commenter_n_key = "<C-w>"
let g:commenter_i_key = "<C-w>"
let g:commenter_v_key = "<C-w>"
```
https://github.com/aben20807/vim-commenter/commit/0d1c41d671ba2d2415621ab195c7818b6a5952f7#diff-46c2a328e36ecbe48644caddcdb0c361R83
